### ISSUE TITLE
Create a utils.py file that provide the data requested.

### ISSUE THREAD

**Issue by a12baghel2** [a12baghel2/STAR_WARS_info#2]
# Task is to retrieve data from the the data folder and provide it to user in JSON format.

**Comment by georgemunyoro** [comment]
I'm interested in working on this. What database is being used?

**Comment by a12baghel2** [comment]
Yes go ahead. Don't use any data base. Retrieve data from data folder.

**Comment by georgemunyoro** [comment]
Awesome!

**Comment by katariarajat** [comment]
hey ,I'm wanted to work on it
